### PR TITLE
Reducing number of problem instances in Fourier-Motzkin projection

### PR DESCRIPTION
**Pull request by krooken**
Added what I think is a missing minus sign. Without it, there are multiples of some rows in the problem matrix.

### CODE REVIEW

**Comment by murrayrm** [comment]
I agree with the change.  This would be a good opportunity to add a unit test that fails on the original code but succeeds on the new code, as a way of increasing unit test coverage (which right now is quite poor).

@krooken Would you have time to do that?  If not, we can merge as is, I think.

**Comment by krooken** [comment]
I'll take a look. I can spend some time, but I found it through inspection, so I am not sure if I can find a failing case. I think it has more to do with performance and less with correctness.

**Comment by murrayrm** [comment]
In that case, maybe just create some unit tests that cover the code and don't worry about something that is different for the prior version.

**Comment by krooken** [comment]
Sure, I'll see what I can do.

**Comment by krooken** [comment]
I've added some tests, so this is ready for review now.

**Comment by slivingston** [comment]
@krooken The square and triangle test cases in R^2 are good: easy to visualize and minimal in terms of number of dimensions.

**Comment by slivingston** [comment]
While merging this, I renamed the tests to have the style of "test_" prefix instead of "_test" suffix.

**Pull request merged**
