### PR TITLE
Update usage of cvxopt.solvers.lp

### PR DESCRIPTION
**Pull request by slivingston**
Copied from the commit message <https://github.com/tulip-control/polytope/commit/033d73c73a0a3293d37469c52f5df442081e24c6>:

> Going from version 1.1.8 to 1.1.9, the API of cvxopt changed and broke positional usage of cvxopt.solvers.lp().
>
> This changeset recovers intended usage by introducing keywords in calls to cvxopt.solvers.lp(). Using keywords instead of purely positional arguments (parameters) should provide some additional protection against unexpected API breaks.

Does anyone have comments about this change? It is compatible with `cvxopt` version 1.1.8, too. For comparison, consider the definitions of `cvxopt.solvers.lp` in

* [version 1.1.8](https://github.com/cvxopt/cvxopt/blob/1.1.8/src/python/coneprog.py#L2548), and
* [version 1.1.9](https://github.com/cvxopt/cvxopt/blob/1.1.9/src/python/coneprog.py#L2550)

### CODE REVIEW

**Comment by carterbox** [comment]
The first commit is addressing problems related to cvxopt/cvxopt#80, but the second commit is a separate issue. Would it be appropriate to notify the `cvxopt` devs should be notified that they broke their API. Perhaps they will patch it or make an appropriate semantic version jump to v2.0.0.

**Comment by slivingston** [comment]
It would be appropriate to notify the `cvxopt` developers about the API break. I commented on the relevant commit of the cvxopt repo: https://github.com/cvxopt/cvxopt/commit/873de3d9091e0bc6ccd0df8c6279fdabf9fb6f53#commitcomment-20446901

**Comment by slivingston** [comment]
My comment about using at least version 1.2.0 in `cvxopt` [was positively acknowledged](https://github.com/cvxopt/cvxopt/commit/873de3d9091e0bc6ccd0df8c6279fdabf9fb6f53#commitcomment-20463287). Nonetheless, I propose that my second commit in this pull request is well motivated while `cvxopt` version 1.1.9 remains the current release.

**Comment by johnyf** [comment]
I agree that the use of keyword arguments is well motivated.

**Pull request merged**
