### PR TITLE
MNT: Make `is_convex` consistently return something of type `(result, envelope)`

### PR DESCRIPTION
**Pull request by knappa**
The function `is_convex` has an inconsistent return type, returning either a boolean or a tuple. This causes the tuple unpacking at line 1226 to fail:
https://github.com/tulip-control/polytope/blob/beadd1263adda6093c8ced3db1afd1a6ceeb069c/polytope/polytope.py#L1226
when either 
https://github.com/tulip-control/polytope/blob/beadd1263adda6093c8ced3db1afd1a6ceeb069c/polytope/polytope.py#L999-L1000
or
https://github.com/tulip-control/polytope/blob/beadd1263adda6093c8ced3db1afd1a6ceeb069c/polytope/polytope.py#L1001-L1002
is triggered.  As mentioned in @johnyf 's comment below, the first of these tests is in error as polytopes that are not full-dimensional can be convex. The updated PR deletes the erroneous test.

### CODE REVIEW

**Comment by knappa** [comment]
Also, I think that a related error occurs at 
https://github.com/tulip-control/polytope/blob/beadd1263adda6093c8ced3db1afd1a6ceeb069c/polytope/polytope.py#L1015-L1016
as `outer.diff(reg)` should have a higher co-dimension than `reg`, but the test as-written will only produce the correct result when `reg` is itself full-dimensional. I'm leaving this one alone, as I don't know how you want to fix that.

**Comment by victoraalves** [comment]
Hi all,

I also came across this bug when trying to create a polytope as a union of other ones, due to the OP's same reason . I see that the PR is still pending. Are there any updates or foreseeable releases in the near future fixing this in Polytope?

Thanks in advance.

**Comment by slivingston** [comment]
> I see that the PR is still pending. Are there any updates or foreseeable releases in the near future fixing this in Polytope?

@victoraalves My best estimate is that we will work on this in the next 3 days.

**Comment by slivingston** [comment]
@knappa thanks for this pull request.
@victoraalves thanks for the ping.
@johnyf thanks for the careful review.

**Comment by slivingston** [comment]
## Regarding the [comment above](https://github.com/tulip-control/polytope/pull/72#issuecomment-956356328) about the `if is_fulldim(outer.diff(reg))` branch

If `reg` is not full-dimensional, then `outer` is an empty instance of `Polytope` because `envelope()` calls `is_fulldim()` before returning: https://github.com/tulip-control/polytope/blob/299ac23db17b5e0a51a01cf6c93599c3472aba49/polytope/polytope.py#L1461-L1464
Then, `is_empty(outer)` on [the next line](https://github.com/tulip-control/polytope/blob/299ac23db17b5e0a51a01cf6c93599c3472aba49/polytope/polytope.py#L1000) will be `True`, resulting in a return value of `False, None`. Therefore, the branch in question will not be reached when `reg` is not full-dimensional. Here is an example:

```py
import numpy as np
import polytope as pc

a = np.array([[1, 1], [-1, -1]])
b = np.array([1, -1])
p = pc.Polytope(a, b)
r = pc.Region([p])

print(r)
#	 Polytope number 1:
#	 Single polytope 
#		  [[ 0.70711  0.70711] x <= [[ 0.70711]
#		   [-0.70711 -0.70711]]|     [-0.70711]]

print(pc.is_fulldim(r))
# False

print(pc.is_convex(r))
# (False, None)
```

## Regarding how I merged this PR

It would have resulted in a more concise commit history if I did a squash-and-merge. However, doing that would cause the commit signatures in this PR to be lost. Given no clear best choice, I did a simple merge.

**Pull request merged**
