### PR TITLE
Create contributing guidelines markdown file

### PR DESCRIPTION
**Pull request by carterbox**
[Fun fact](https://github.com/blog/1184-contributing-guidelines), you can put a file call contributing in your repository, and it will be linked to the "open a pull request page".

I would have appreciated being able to easily locate this information, and others may as well.

### CODE REVIEW

**Comment by johnyf** [comment]
Thank you for noting this possibility. It raises a good point. We are aware of this mechanism, and in a discussion with @slivingston (not too long ago), we considered using a `CONTRIBUTING.md` file for `tulip` (I think the conclusion was to consider it further). I am skeptical about it, because of the additional file. To ameliorate the clutter, it could be hidden under [`.github/`](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

About the text of 15e70c2a4ab59d90ea810f5c06f2737a168defa7 (which includes my comment from https://github.com/tulip-control/polytope/pull/33#issuecomment-273382640), the way I describe commit abbreviations was:

1. informal: In order to document them for reference by others, I would need to be more precise (and think more carefully about conflicts and other decisions), at least for those that don't originate from `numpy`'s documentation.

2. personal: I should clarify that "I use" was intended to mean that we have never had a discussion (or my memory fails me) with other developers involved in the `tulip` and `polytope` projects about whether to use commit abbreviations, and which ones. Perhaps some people prefer to not use abbreviations, or different rules for abbreviations.

In view of the above, it is better to present these abbreviations as recommendations. Also, I think that the section about commit abbreviations would be better located in `tulip`'s developer guide (if others agree to place it somewhere at all). I would be happy to add it there, but I may need some time to come up with a more precise description.

The initial section can be simplified to a pointer to what development practices are followed in this project. From the discussion I mentioned above, I recall also some other points that are relevant to pull requests, for example the need to:

1. provide passing tests
2. document any additions
3. adhere to PEP 8 style conventions (which appears also in the developer's guide, but some times needs to be emphasized)
4. use informative commit messages
5. tidy commit history

**Comment by slivingston** [comment]
regarding abbreviations, I do not remember deciding to preferentially use it. I began to use it (here and elsewhere) after I realized how it can help when I am reviewing commit history.

I agree with [the comment above](https://github.com/tulip-control/polytope/pull/38#issuecomment-273972278) by @johnyf that using these is recommended, not required. To me, it is more important to follow best practices for writing commit messages.

**Comment by slivingston** [comment]
@johnyf I think that it would be useful to copy your comment from <https://github.com/tulip-control/polytope/pull/33#issuecomment-273382640> into the TuLiP developer's guide. There is already some text about these abbreviations ("Prefix commits to classify the changes..."). You can expand it into a subsection of the informal "Advice" section.

**Comment by slivingston** [comment]
As for the placement of the file, I am happy with a top-level CONTRIBUTING.md. The alternative (under the directory `.github`) is hidden, which indeed removes clutter, but it links the project to GitHub in a special way that makes interaction with source code less enjoyable.

**Comment by johnyf** [comment]
I will go ahead to prepare and add recommendations about specific commit abbreviations to the `tulip` developer's guide. I am OK for a top-level `CONTRIBUTING.md`. It is also more readily visible in clones.

Indeed, commit abbreviations help a lot with reviewing history. Using them makes frequent (private) rebasing much easier. It also aids in quickly inspecting history when looking for something (assuming `grep`ing the history isn't applicable).

**Comment by carterbox** [comment]
## actions
I can remove the `commit tags` section from `CONTRIBUTING.md`, but leave introduction with the link to the `tulip-control` docs. That way, y'all can update the documents page and the style guide changes for both projects simultaneously.

Probably, the docs page for `tulip-control` should be rewritten to better communicate the [listed expectations](https://github.com/tulip-control/polytope/pull/38#issuecomment-273972278) summarized here.

## questions
One thing I didn't understand from the `tulip-control` style guide is the difference between the `Epydoc` API documentation and the user and developers guide using `Sphinx`. Why are these things separate? Which functions are documented with which syntax?

**Comment by johnyf** [comment]
I may edit the commit too upon merging, so either is fine with me.

[`epydoc`](http://epydoc.sourceforge.net/) generates [API documentation](https://tulip-control.sourceforge.io/api-doc/tulip-module.html) automatically from the code's docstrings. [`sphinx`](http://www.sphinx-doc.org/en/1.5.1/) processes the separate `*.rst` files to produce [documentation](https://tulip-control.sourceforge.io/doc/) that may not include any docstrings at all. The API docs are like a reference form for the code, with documentation extracted from it. Sphinx is designed to process document-style source. It can generate API documentation too, but can also process more general documents.

In the projects I've written documentation for from scratch, I wrote one single Markdown document (in the spirit of [`ply`'s documentation](http://www.dabeaz.com/ply/ply.html)). Also, I tend to use Markdown within docstrings, together with some of epydoc's annotations ([example docstring](https://github.com/johnyf/dd/blob/01d917382cad24f0d48cde3f2ea2759e8a9a5544/dd/bdd.py#L619)), in anticipation of the day that a Markdown-capable epydoc-like API generator will be available.

Of course, I don't mix Markdown and Epydoc markup in projects that have already been using Epydoc markup (if needed in the future, an automated lexical translation is probably straightforward). Usually, I read docstrings by browsing the source code of a project. Interesting related projects:

- [`pdoc`](https://github.com/BurntSushi/pdoc) (may be sufficiently developed to replace `epydoc` and understand Markdown)
- [`pycco`](https://github.com/pycco-docs/pycco)
- [`pyccoon`](https://github.com/ckald/pyccoon)
- [`pyliterate`](https://github.com/bslatkin/pyliterate)

A Markdown interface for sphinx [appears](http://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst) to also be an option.

**Comment by slivingston** [comment]
@carterbox For this PR it will not be necessary to spin CI jobs, which you can avoid by adding `[ci skip]` (as described at <https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build>).

**Comment by johnyf** [comment]
Merged to branch `dev` as c2f238ee93961c7d4731943dc60c718971a7a1f6. In case we would like to add some item that I forgot about to the checklist, we can squash the additions upon merging to `master`.

Other comments: Placing the directive `[ci skip]` on a line other than the commit message's title makes it easier to inspect history. The upper bound on line width applies to all files.

**Pull request closed without merging**
