### PR TITLE
Added assert to check non-zero, non-colinear u,v

### PR DESCRIPTION
**Pull request by drscotthawley**
How well does this satisfy your TODO?

### CODE REVIEW

**Review by slivingston — CHANGES_REQUESTED** [review]
Thanks for proposing to handle this TODO. Comments:

* First and foremost, I wonder whether this TODO is to-be-done. The non-parallel assertion does not seem to be prerequisite, but I did not prove it. I tried several examples, and the resulting rotation matrix is approximately the identity. Can you confirm this? Similarly, nonzero vectors does not seem to be prerequisite, but I did not prove it.
* Raise `ValueError` to indicate something is wrong with the arguments (ref: <https://docs.python.org/3/library/exceptions.html#ValueError>).
* After the TODO is done, simply delete the original TODO comment, instead of removing only the "TODO" part.

**Comment by slivingston** [comment]
If indeed the algorithm allows the vectors to be zero or parallel, then this function should not raise an exception. However, the resulting matrix may have some numerical error (i.e., not exactly be the identity). Likely the user should instead call `np.eye()` to create a rotation matrix or not "rotate" at all, so I recommend that a warning is logged.

**Comment by drscotthawley** [comment]
Oooo excellent points, thank you.  Failing an assert is overly harsh, in retrospect. 
It would make sense that if u & v are (anti-)parallel, it should just return the (negative) identity matrix.
UserWarning in the case of a zero vector seems good.   
I'll work on those changes and resubmit.  And even then, no worries if my changes aren't your cup tea. I just saw something I could add quickly.

**Comment by drscotthawley** [comment]
After doing some more checking, it seems the algorithm already robustly returns an identify matrix for the cases of zero or (anti-)parallel vectors.  Thus one can, if one wants, add a check such as in the new revision in order to save time. 
It is, however, not necessary.

**Review by slivingston — APPROVED** [review]
@drscotthawley Thanks! This change is useful. Eventually I want to do performance profiling for all of this package, at which time we can revisit whether the `norm()` here adds too much time compared to the precision benefit of having it.

**Pull request merged**
